server:
  port: 8005

spring:
  application:
    name: GUFL_kongliang
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://134.175.220.159:3306/kl_dev
    username: root
    password: klklKL889
  profiles:
    active: dev
  redis:
    host: 134.175.220.159
    port: 6379
    password: klklKL889
    database: 0

logging:
  level:
    com.app.mapper: debug


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.GUFL_kongliang.entity
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#pagehelper分页助手
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tSqeB6F
      keysecret: yV3YNRDethGC0O8OiaqwWeTcwvtFZQ
      bucketname: kongliang-test
      filehost: active
